"""Production schema migration for PostgreSQL."""
from alembic import op
import sqlalchemy as sa
revision = "0002_production_schema"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer, primary_key=True), sa.Column("telegram_id", sa.BigInteger, nullable=False), sa.Column("first_name", sa.String(128), nullable=False, server_default=""), sa.Column("username", sa.String(128)), sa.Column("is_blocked", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("telegram_id"))
    op.create_table("wallets", sa.Column("id", sa.Integer, primary_key=True), sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("balance", sa.Numeric(18, 2), nullable=False, server_default="0"), sa.UniqueConstraint("user_id"), sa.CheckConstraint("balance >= 0", name="ck_wallet_nonnegative"))
    op.create_table("ledger_entries", sa.Column("id", sa.Integer, primary_key=True), sa.Column("wallet_id", sa.Integer, sa.ForeignKey("wallets.id"), nullable=False), sa.Column("amount", sa.Numeric(18, 2), nullable=False), sa.Column("balance_after", sa.Numeric(18, 2), nullable=False), sa.Column("kind", sa.String(32), nullable=False), sa.Column("idempotency_key", sa.String(128), nullable=False), sa.Column("reference", sa.String(128)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("idempotency_key"))
    op.create_table("topups", sa.Column("id", sa.Integer, primary_key=True), sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False), sa.Column("amount", sa.Numeric(18, 2), nullable=False), sa.Column("receipt_file_id", sa.String(256), nullable=False), sa.Column("receipt_mime_type", sa.String(64), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="pending"), sa.Column("decision_key", sa.String(128), unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.CheckConstraint("amount > 0", name="ck_topup_positive"))
    op.create_table("products", sa.Column("id", sa.Integer, primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("volume", sa.String(64), nullable=False), sa.Column("duration", sa.String(64), nullable=False), sa.Column("price", sa.Numeric(18, 2), nullable=False), sa.Column("available", sa.Boolean, nullable=False, server_default=sa.true()), sa.CheckConstraint("price > 0", name="ck_product_positive_price"))
    op.create_table("configs", sa.Column("id", sa.Integer, primary_key=True), sa.Column("product_id", sa.Integer, sa.ForeignKey("products.id"), nullable=False), sa.Column("value", sa.Text, nullable=False), sa.Column("assigned", sa.Boolean, nullable=False, server_default=sa.false()), sa.UniqueConstraint("value", name="uq_config_value"))
    op.create_table("orders", sa.Column("id", sa.Integer, primary_key=True), sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False), sa.Column("product_id", sa.Integer, sa.ForeignKey("products.id"), nullable=False), sa.Column("amount", sa.Numeric(18, 2), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="paid"), sa.Column("payment_key", sa.String(128), nullable=False), sa.Column("config_id", sa.Integer, sa.ForeignKey("configs.id"), unique=True), sa.Column("delivery_status", sa.String(16), nullable=False, server_default="pending"), sa.Column("delivered_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("payment_key"))

def downgrade():
    for table in ("orders", "configs", "products", "topups", "ledger_entries", "wallets", "users"): op.drop_table(table)
